### ISSUE TITLE
SQS Consumer 구조 설계

### ISSUE THREAD

**Issue by BaekGeunYoung** [BaekGeunYoung/stress-ticket-reservation-worker#1]
sqs로부터 큐 메세지를 받아 멀티스레드 환경에서 작업을 처리하는 sqs consumer의 구성 요소는 아래와 같다.
- Queue message receiver
    + sqs로부터 큐메세지를 받아와서 이를 channel로 넘겨줌.
- Channel
    + message receiver와 worker가 큐메세지를 주고 받기 위한 layer.
- Processor
    + message receiver가 넘겨주는 큐메세지를 channel로부터 전달받아 실제로 작업을 수행하는 layer. 멀티스레드 환경(정확히는 coroutine)이므로 여러 개의 processor가 동시에 돌아감.

전체적인 Consumer 구조의 다이어그램은 아래와 같다.
![image](https://user-images.githubusercontent.com/40847155/71304416-c49ab400-2409-11ea-8901-67a02b41081b.png)

**Comment by SeoSeongHo** [comment]
좋습니다 ~~
